SELECT nlp_cui,
 nlp_pretty_name,
 CAST(nlp_end as INT) as nlp_end,
 nlp_types,
 nlp_detected_name,
 nlp_meta_anns_Presence_confidence,
 nlp_meta_anns_Presence_name,
 nlp_meta_anns_Presence_value,
 nlp_meta_anns_Time_confidence,
 nlp_meta_anns_Time_name,
 nlp_meta_anns_Time_value,
 nlp_meta_anns_Subject_confidence,
 nlp_meta_anns_Subject_name,
 nlp_meta_anns_Subject_value,
 service_version,
 CAST(nlp_start AS INT) as nlp_start,
 nlp_source_value,
 nlp_id,
 meta_note_id,
 service_model,
 meta_subject_id,
 nlp_acc,
 nlp_type_ids,
 nlp_context_similarity,
 nlp_ontologies,
 timestamp
FROM {{ source('mimic', 'radiology_annotations') }}